### ISSUE TITLE
Workflow unclear to make `ros2 topic echo` work for custom-generated types

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake-ros#118]
In Anzu PR 9310, unable to use it for custom generated type; not immediately clear to me how to make this work.

FYI @sloretz @cottsay 
\cc @IanTheEngineer @calderpg-tri

**Comment by EricCousineau-TRI** [comment]
It seems like the right workflow is to ensure the Python messages are on `PYTHONPATH` when running the `ros2` CLI:
3ffdb67
That at least makes `ros2 topic echo` work.

However, `ros2 interfaces list` does not work: 71c9e27
How do we update this to ensure that our messages etc. are discoverable?

**Comment by sloretz** [comment]
> How do we update this to ensure that our messages etc. are discoverable?

The messages are made discoverable via the ament index. This is normally created via [this bit of CMake code](https://github.com/ros2/rosidl/blob/b8381d955a111cdf8a52a0f1891cc55de5f19db1/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake#L236-L252). There doesn't seem to be an equivalent in `bazel_ros2_rules`, but maybe [it could exist here](https://github.com/RobotLocomotion/drake-ros/blob/416cf8b81ad3e9c2d6855e2f43a5380328401ffa/bazel_ros2_rules/ros2/rosidl.bzl#L157) so that depending on `:custom_messages_defs` gave a target the ability to discover those messages. If so the key pieces are to generate ament_index files for custom messages, and to make the shim update the `AMENT_PREFIX_PATH` environment variables to point to those files when `:custom_messages_defs` is depended upon.

**Comment by sloretz** [comment]
Fixed by #124
